# Generated by Django 3.2.4 on 2021-07-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('idCarrusel', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_carrusel')),
                ('textoCarrusel', models.CharField(max_length=50, verbose_name='Texto_carrusel')),
                ('imagenCarrusel', models.ImageField(null=True, upload_to='carrusel')),
            ],
        ),
    ]
