# Generated by Django 3.2.4 on 2021-07-08 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrusel',
            name='imagenCarrusel',
        ),
    ]
