# Generated by Django 3.2.4 on 2021-07-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_acercade_redessociales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redessociales',
            name='idRedes',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Id_redes'),
        ),
    ]
