# Generated by Django 3.2.4 on 2021-07-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_redessociales_idredes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RedesSociales',
        ),
        migrations.AddField(
            model_name='acercade',
            name='fotoSiguenos',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
