# Generated by Django 3.2.4 on 2021-07-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210708_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acercade',
            name='fotoSiguenos',
            field=models.ImageField(null=True, upload_to='imgRedes'),
        ),
        migrations.AlterField(
            model_name='acercade',
            name='imagenLogo',
            field=models.ImageField(null=True, upload_to='imgLogo'),
        ),
    ]
