# Generated by Django 3.2.4 on 2021-07-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210711_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioContacto',
            fields=[
                ('idFormulario', models.IntegerField(primary_key=True, serialize=False, verbose_name='IdFormulario')),
                ('nombreFormulario', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellidoFormulario', models.CharField(max_length=20, verbose_name='Apellido')),
                ('emailFormulario', models.CharField(max_length=20, verbose_name='Email')),
                ('comentarioFormulario', models.CharField(max_length=20, verbose_name='Comentario')),
            ],
        ),
    ]
