# Generated by Django 3.2.4 on 2021-07-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_formulariocontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajos',
            fields=[
                ('idCarta', models.IntegerField(primary_key=True, serialize=False, verbose_name='IdCarta')),
                ('imagenTrabajo', models.ImageField(null=True, upload_to='imgTrabajos')),
                ('tituloTrabajo', models.CharField(max_length=50, verbose_name='Nombre Trabajo')),
                ('diagnostico', models.CharField(max_length=50, verbose_name='Diagnostico')),
                ('mecanico', models.CharField(max_length=50, verbose_name='Mecanico')),
                ('fecha', models.CharField(max_length=30, verbose_name='Fecha')),
                ('listadoMateriales', models.CharField(max_length=100, verbose_name='Listado Materiales')),
            ],
        ),
    ]
